# Generated by Django 2.1.7 on 2020-05-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20200527_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='users',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
