# Generated by Django 2.1.7 on 2020-05-30 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
