# Generated by Django 2.1.7 on 2020-05-30 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20200530_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='following',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
