# Generated by Django 2.1.7 on 2020-05-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_auto_20200530_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='username',
        ),
    ]
