# Generated by Django 2.1.7 on 2020-06-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20200601_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='following',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
